### PR TITLE
Fix for #3

### PR DESCRIPTION
**Pull request by christopherraa**
This is a really simple fix with two tests that resolves the issue with double included css and javascript.

### CODE REVIEW

**Comment by spurkis** [comment]
Thanks for the PR, @christopherraa - would you like a commit bit on the project + CPAN co-maintenance privs?

**Comment by christopherraa** [comment]
Thank you for the vote of confidence. :) I have never contributed directly to anything on CPAN and do not yet have a PAUSE id. I have applied though, but they say in their docs that it might take three weeks to process the application. I'll update you when I hear from them.

**Comment by christopherraa** [comment]
Got my PAUSE id real quick: CRORAA

**Comment by christopherraa** [comment]
@spurkis Any update on this?

**Comment by spurkis** [comment]
Hi @christopherraa, I've sorted out co-maint on PAUSE and github, quick code review looks good so merged.  Let me know if you need a hand with the module creation & PAUSE upload process.

**Comment by renormalist** [comment]
I'm a legacy user of this module in a legacy codebase. There might be some smaller fixes coming up from our side.
If you still read this, @spurkis , you might also want to give me co-maint status, then I might step in and release a new version to cpan. My PAUSE handle is SCHWIGON. 

Maybe I can even take care of the other pull requests, but I don't promise it yet. Energy level, u know...

**Comment by spurkis** [comment]
Hi @renormalist, good to hear from you, I hope you're well!
I've added you as a co-maintainer on CPAN & github for this module.  Totally get it re: energy levels, I've not had spare capacity for open source work for quite a while now, but I'm glad people still find the code useful.

**Comment by renormalist** [comment]
Thanks. A new release 0.12 is on its way to CPAN. I hope I didn't screw up too much.

**Pull request merged**
